from urlparse import urlparse
# Detection function for Wordpress.
from cmspwn.module import pwnfunc

@pwnfunc
def is_wordpress(cmspwn,response):
    urlp = urlparse(response.url)
    wp_content_url = "{0}://{1}/wp-content/".format(urlp.scheme, urlp.netloc)
    wp_includes_url = "{0}://{1}/wp-includes/".format(urlp.scheme, urlp.netloc)
    identify_strings = ("<!-- This site is optimized with the Yoast WordPress",
                        "Cached page generated by WP-Super-Cache",
                        wp_content_url, wp_includes_url, )
    for id_string in identify_strings:
        if id_string in response.content:
           cmspwn.found  = True; cmspwn.Framework = 'Wordpress';cmspwn.site = 'wordpress'
           return
